pantalla:
  ancho: 900
  alto: 700

configuracion:
  vel_personaje: 90
  margen_scroll: 10

tipos:
  - nombre: arbol
    imagen: images/arbol.png

  - nombre: castillo
    alto_base: 3
    ancho_base: 4
    imagen: images/castillo.png
    pixel_ref_x: 30
    pixel_ref_y: 40

  - nombre: soldado
    fps: 40
    imagen: images/soldado2.png

  - nombre: juana_de_arco
    fps: 10
    imagen: images/juana.png

  - nombre: animal
    fps: 20
    delay: 30
    imagen: images/animal.png

  - nombre: tierra
    imagen: images/tierra.png

  - nombre: agua
    imagen: images/agua.png

  - nombre: juanita
    imagen: images/soldier.png

escenario:
  - nombre: orleans
    size_x: 50
    size_y: 50
    entidades:
      - {x: 25, y: 0, tipo: agua}
      - {x: 22, y: 0, tipo: tierra}
      - {x: 4, y: 10, tipo: agua}
      - {x: 0, y: 5, tipo: castillo}
      - {x: 30, y: 12, tipo: tierra}
      - {x: 4, y: 5, tipo: arbol}
      - {x: 4, y: 6, tipo: arbol}
      - {x: 5, y: 5, tipo: arbol}
      - {x: 15, y: 12, tipo: arbol}
      - {x: 5, y: 29, tipo: castillo}
      - {x: 10, y: 14, tipo: animal}
      - {x: 23, y: 23, tipo: juanita}
    protagonista:
      - tipo: soldado
        x: 15
        y: 15
