nombre_jugador: pepe

direccion_ip: 127.0.0.1

pantalla:
  ancho: 800
  alto: 640

configuracion:
  vel_personaje: 50
  margen_scroll: 8
  rango_de_vision: 6

tipos:
  - nombre: arbol
    imagen: images/utils/arbol.png
    descripcion: Arbol
sdasd
  - nombre: tierra
    imagen: images/relieve/tierra.png

  - nombre: agua
    imagen: images/relieve/agua.png

  - nombre: centro_civico
    alto_base: 4
    ancho_base: 4
    imagen: images/utils/Barracks3.png
    descripcion: Centro_Civico

  - nombre: cuartel
    alto_base: 4
    ancho_base: 4
    imagen: images/utils/Barracks7.png
    descripcion: Cuartel

  - nombre: barraca
    alto_base: 4
    ancho_base: 4
    imagen: images/utils/Barracks5.png
    descripcion: Barraca_Arquero

  - nombre: soldado
    fps: 15
    imagen: images/sprites/soldado_camina.png
    descripcion: Soldado

  - nombre: arquero
    fps: 20
    imagen: images/sprites/arquero_camina.png
    descripcion: Arquero

  - nombre: animal
    delay: 5000
    fps: 10
    imagen: images/sprites/vaca_come.png
    descripcion: Animal

  - nombre: barraca
    alto_base: 4
    ancho_base: 4
    imagen: images/utils/Barracks5.png
    descripcion: Barraca Arquero

#  - nombre: comida
#    imagen: images/comida.png

  - nombre: mina_piedra
    imagen: images/utils/mina_piedra2.png
    descripcion: Mina de piedra

  - nombre: mina_oro
    imagen: images/utils/mina_oro.png

  - nombre: aldeano
    fps: 40
    imagen: images/sprites/aldeano_camina.png
    descripcion: Aldeano

  - nombre: construccion
    imagen: images/utils/Barracks3.png #!!!
    descripcion: Construcci√≥n

escenario:
  - nombre: orleans
    size_x: 50
    size_y: 50
    entidades:
      - {x: 15, y: 15, tipo: aldeano}
      - {x: 10, y: 10, tipo: agua}
      - {x: 10, y: 11, tipo: agua}
      - {x: 10, y: 12, tipo: agua}
      - {x: 11, y: 10, tipo: agua}
      - {x: 11, y: 11, tipo: agua}
      - {x: 11, y: 12, tipo: agua}
      - {x: 12, y: 10, tipo: agua}
      - {x: 12, y: 11, tipo: agua}
      - {x: 12, y: 12, tipo: agua}
      - {x: 22, y: 0, tipo: tierra}
      - {x: 30, y: 12, tipo: tierra}
      - {x: 5, y: 5, tipo: arbol}
      - {x: 6, y: 5, tipo: arbol}
      - {x: 7, y: 5, tipo: arbol}
      - {x: 5, y: 6, tipo: arbol}
      - {x: 6, y: 6, tipo: arbol}
      - {x: 7, y: 6, tipo: arbol}
      - {x: 1, y: 0, tipo: arbol}
      - {x: 1, y: 1, tipo: arbol}
      - {x: 10, y: 14, tipo: animal}
      - {x: 11, y: 14, tipo: animal}
      - {x: 12, y: 14, tipo: animal}
