pantalla:
  ancho: 800
  alto: 600

configuracion:
  vel_personaje: 10
  margen_scroll: 50

tipos:
  - nombre: arbol
    imagen: images/arbol.png

  - nombre: castillo
    alto_base: 3
    ancho_base: 4
    imagen: images/castillo.png
    pixel_ref_x: 30
    pixel_ref_y: 40

  - nombre: soldado
    delay: 50
    fps: 40
    imagen: images/soldado.png

  - nombre: juana_de_arco
    fps: 10
    imagen: images/juana.png

  - nombre: tierra
    imagen: images/tierra.png

  - nombre: agua
    imagen: images/agua.png

escenario:
  - nombre: orleans
    size_x: 30
    size_y: 30
    entidades:
      - {x: 25, y: 0, tipo: agua}
      - {x: 22, y: 0, tipo: tierra}
      - {x: 4, y: 10, tipo: agua}
      - {x: 4, y: 11, tipo: castillo}
      - {x: 30, y: 12, tipo: tierra}
      - {x: 4, y: 5, tipo: arbol}
      - {x: 4, y: 6, tipo: arbol}
      - {x: 5, y: 5, tipo: arbol}
      - {x: 15, y: 12, tipo: arbol}
      - {x: 0, y: 10, tipo: castillo}
    protagonista:
      - tipo: soldado	#juana_de_arco
        x: 25
        y: 25
